remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme

title: Vedant's GitHub Page
description: Personal website showcasing projects, blogs, and more

# Navigation Links
header_links:
  - title: About Me
    url: /
  - title: Projects
    url: /cryptosystems-project
  - title: Contact Me
    url: /#contact
  - title: Blog
    url: /Session_Reports/

